"""Build the two training notebooks.

Written as a generator rather than by hand-editing .ipynb JSON: notebooks are a terrible diff
format, and both notebooks share most of their setup, so the shared parts should exist once.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = "https://github.com/GhanaNLP/stable-twi-tts"
MODEL = "ghanaopendata/stable-twi-tts"
DATASET = "ghanaopendata/new-twi-tts-aligned-ipa"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "outputs": [], "source": list(lines)}


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python",
                           "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
            "accelerator": "GPU",
            "colab": {"provenance": [], "gpuType": "A100"},
        },
        "nbformat": 4,
        "nbformat_minor": 0,
    }


# --------------------------------------------------------------------- shared

GPU_CHECK = code(
    "# A GPU is required. On Colab: Runtime -> Change runtime type -> GPU.\n",
    "!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader\n",
    "import torch; print('torch', torch.__version__, '| cuda', torch.cuda.is_available())",
)

INSTALL = code(
    "# Piper's trainer, plus the two phonemisers. This takes a few minutes.\n",
    "!apt-get -qq install -y espeak-ng > /dev/null\n",
    "!git clone -q https://github.com/OHF-Voice/piper1-gpl.git\n",
    "!pip install -q -e './piper1-gpl[train]'\n",
    "\n",
    "# ghana-g2p for Twi. Installed from source because africa-g2p's wheel build is broken\n",
    "# upstream (it ships data/ twice, so hatchling refuses the archive).\n",
    "!git clone -q https://github.com/AfriSpeech/africa-g2p.git\n",
    "!git clone -q https://github.com/GhanaNLP/ghana-g2p.git\n",
    "import sys; sys.path[:0] = ['africa-g2p/src', 'ghana-g2p/src']\n",
    "from ghana_g2p import GhanaG2P\n",
    "print('twi g2p:', GhanaG2P('Asante Twi').ipa('Akwaaba', sep=' '))",
)

MONOTONIC = code(
    "# VITS needs a Cython extension that pip does not build, and whose absence only shows up\n",
    "# as ModuleNotFoundError once training starts. Build it now.\n",
    "!pip install -q cython\n",
    "%cd piper1-gpl/src\n",
    "!python piper/train/vits/monotonic_align/setup.py build_ext --inplace 2>&1 | tail -2\n",
    "# Upstream's __init__ imports from a nested path the build does not create.\n",
    "!sed -i 's/^from \\\\.monotonic_align\\\\.core import/from .core import/' \\\n",
    "    piper/train/vits/monotonic_align/__init__.py\n",
    "%cd /content\n",
    "import torch\n",
    "sys.path.insert(0, 'piper1-gpl/src')\n",
    "from piper.train.vits import monotonic_align\n",
    "print('monotonic_align ok', monotonic_align.maximum_path(\n",
    "    torch.zeros(1, 3, 5), torch.ones(1, 3, 5)).shape)",
)

CLONE_TOOLS = code(
    f"!git clone -q {REPO}.git\n",
    "import sys; sys.path.insert(0, 'stable-twi-tts')\n",
    "!ls stable-twi-tts/training",
)

PITFALLS = md(
    "## Five things that fail silently\n",
    "\n",
    "Each of these cost this project real time. None of them raise an error — they produce\n",
    "fluent-sounding wrong audio, which is much more expensive than a crash.\n",
    "\n",
    "1. **Phonemise with the same function at training and inference.** We trained on\n",
    "   ASR-derived phonemes and synthesised from G2P-derived ones. They disagreed on 26% of\n",
    "   units for Twi and 51% for English, and TTS phoneme error tracked it almost exactly\n",
    "   (25.6% vs 68.6%). Nothing errored.\n",
    "2. **Clear the phoneme cache when you change the id map.** Piper caches phoneme tensors\n",
    "   keyed by *text*, not by ids. Change the map and the stale tensors are silently reused,\n",
    "   so you train on the old targets believing you changed them. Delete `cache/*.phonemes.pt`\n",
    "   and keep `*.audio.pt` — the audio cache is the expensive one.\n",
    "3. **Never split IPA by character.** Units like `kʰ`, `t͡ʃ`, `k͡p`, `aɪ` are single symbols.\n",
    "4. **Don't early-stop on `val_mel`.** It saturates while the adversarial losses are still\n",
    "   removing artifacts. Keep top-k by `val_mos` too, and measure round-trip phoneme error.\n",
    "5. **Resize the speaker table before loading a checkpoint with a different speaker count** —\n",
    "   otherwise the load fails, or worse, silently ignores the speaker id.\n",
)


def data_prep(scratch: bool) -> list[dict]:
    """Data preparation is identical either way — only the checkpoint differs."""
    return [
        md("## 1. Get the data\n",
           "\n",
           f"[`{DATASET}`]({'https://huggingface.co/datasets/' + DATASET}) carries audio, text\n",
           "and IPA together. It is ~23 GB, so on Colab mount Drive or use a subset first.\n"),
        code("from huggingface_hub import snapshot_download\n",
             "\n",
             "# Start with a few shards to check the pipeline end to end before committing to 23 GB.\n",
             "SHARDS = 4        # set to None for the whole dataset\n",
             f"repo = '{DATASET}'\n",
             "patterns = [f'data/train-{i:05d}-*' for i in range(SHARDS)] if SHARDS else None\n",
             "path = snapshot_download(repo, repo_type='dataset', local_dir='data',\n",
             "                         allow_patterns=patterns)\n",
             "!ls data/data | head -5 && du -sh data"),
        md("## 2. Export wavs and a manifest\n",
           "\n",
           "One shared wav directory at 22.05 kHz, plus a manifest. 22.05 kHz because the Piper\n",
           "checkpoints we finetune from are 22.05 kHz — resampling once here beats fighting it later.\n"),
        code("!python stable-twi-tts/training/tts_data.py wavs \\\n",
             "    --data data/data --out tts22k --sr 22050 --threads 8\n",
             "!head -2 tts22k/manifest.tsv | cut -c1-120"),
        md("## 3. Phonemise from text\n",
           "\n",
           "**This is the step that decides whether the model works.** Targets come from the same\n",
           "phonemiser used at inference — ghana-g2p for Twi, espeak-ng for English — so there is no\n",
           "train/inference gap by construction.\n"),
        code("!python stable-twi-tts/training/retarget_g2p.py \\\n",
             "    --data tts22k --piper-src piper1-gpl/src\n",
             "!wc -l tts22k/metadata_train_g2p.csv tts22k/phonemes_g2p.json"),
    ]


# ------------------------------------------------------------------ finetuning

FINETUNE = notebook([
    md("# Finetune the Twi TTS model\n",
       "\n",
       f"Continue training [`{MODEL}`]({'https://huggingface.co/' + MODEL}) on your own audio —\n",
       "to add a speaker, adapt to a domain, or improve a language it already knows.\n",
       "\n",
       "**Finetuning is almost always the right starting point.** The published checkpoint has\n",
       "already learned Twi phonetics, a 1,555-voice speaker table and a working vocoder. Starting\n",
       "from it converges in hours where from-scratch takes days.\n",
       "\n",
       "Use `train_from_scratch.ipynb` instead only if you are training a *different language* whose\n",
       "phoneme inventory barely overlaps.\n"),
    GPU_CHECK, INSTALL, MONOTONIC, CLONE_TOOLS,
    *data_prep(scratch=False),
    md("## 4. Get the checkpoint and its id map\n",
       "\n",
       "**The phoneme id map is not optional.** The weights encode *id 26 means /n/*. Load them\n",
       "against a different map and the model reads a different language — with no error.\n"),
    code("from huggingface_hub import hf_hub_download\n",
         f"repo = '{MODEL}'\n",
         "ckpt = hf_hub_download(repo, 'finetune/checkpoint.ckpt')\n",
         "cfg  = hf_hub_download(repo, 'finetune/config.json')\n",
         "phon = hf_hub_download(repo, 'finetune/phonemes.json')\n",
         "print(ckpt)\n",
         "import json; c = json.load(open(cfg))\n",
         "print('speakers', c['num_speakers'], '| symbols', len(c['phoneme_id_map']),\n",
         "      '|', c['audio']['sample_rate'], 'Hz')"),
    md("### Reuse the published id map\n",
       "\n",
       "Keep every existing id fixed. If your data needs symbols the model lacks, add them in the\n",
       "free slots (ids up to 255) and **graft their embeddings** from a pretrained model rather than\n",
       "leaving them random — we measured that as the difference between converging in one epoch and\n",
       "several.\n"),
    code("import shutil, json\n",
         "shutil.copy(phon, 'tts22k/phonemes_g2p.json')   # published map wins\n",
         "\n",
         "# Re-encode the metadata against it, so ids mean what the checkpoint thinks they mean.\n",
         "!python stable-twi-tts/training/retarget_g2p.py \\\n",
         "    --data tts22k --old-map tts22k/phonemes_g2p.json --piper-src piper1-gpl/src\n",
         "print('symbols:', len(json.load(open('tts22k/phonemes_g2p.json'))))"),
    md("## 5. Match the speaker table\n",
       "\n",
       "`emb_g` has one row per speaker, so a different speaker count fails to load. This resizes\n",
       "it and seeds new rows from **real pretrained voices** rather than noise — a new speaker then\n",
       "starts from a coherent voice and moves toward its target, instead of hunting for voice space.\n"),
    code("NSPK = !cut -d'|' -f2 tts22k/metadata_train_g2p.csv | sort -u | grep -c .\n",
         "NSPK = int(NSPK[0]); print('speakers in your data:', NSPK)\n",
         "\n",
         "!python stable-twi-tts/training/adapt_checkpoint.py \\\n",
         "    --ckpt {ckpt} --out adapted.ckpt --num-speakers {NSPK}"),
    md("## 6. Clear the phoneme cache\n",
       "\n",
       "Piper keys its cache on **text**, not on phoneme ids. If you reuse a cache directory after\n",
       "changing the map, stale tensors are silently reused and you train on the old targets.\n"),
    code("!find runs -name '*.phonemes.pt' -delete 2>/dev/null; echo 'phoneme cache cleared'\n",
         "!find runs -name '*.audio.pt' 2>/dev/null | wc -l   # audio cache kept: it is the slow one"),
    md("## 7. Train\n",
       "\n",
       "A finetune wants a **lower learning rate** than from-scratch — the default would undo what\n",
       "the checkpoint knows. `--data.validation_split` is small on purpose: the default validates on\n",
       "thousands of utterances through UTMOS, costing ~20% of throughput for a mean that stabilises\n",
       "in a few hundred.\n"),
    code("!python -m piper.train fit \\\n",
         "    --data.voice_name my_twi_voice \\\n",
         "    --data.csv_path tts22k/metadata_train_g2p.csv \\\n",
         "    --data.audio_dir tts22k/wav \\\n",
         "    --data.dataset_type phoneme_ids \\\n",
         "    --data.phonemes_path tts22k/phonemes_g2p.json \\\n",
         "    --data.espeak_voice en-us \\\n",
         "    --data.phoneme_type text \\\n",
         "    --data.num_symbols 256 \\\n",
         "    --data.cache_dir runs/cache \\\n",
         "    --data.config_path runs/config.json \\\n",
         "    --data.batch_size 24 \\\n",
         "    --data.num_workers 4 \\\n",
         "    --data.validation_split 0.005 \\\n",
         "    --model.num_speakers {NSPK} \\\n",
         "    --model.sample_rate 22050 \\\n",
         "    --model.warmstart_ckpt adapted.ckpt \\\n",
         "    --model.mos_metric utmos \\\n",
         "    --optimizer.lr 5e-5 \\\n",
         "    --trainer.default_root_dir runs \\\n",
         "    --trainer.max_epochs -1 \\\n",
         "    --trainer.precision bf16-mixed \\\n",
         "    --trainer.val_check_interval 1000 \\\n",
         "    --trainer.accelerator gpu --trainer.devices 1"),
    md("Two flags exist only to satisfy the CLI: `--data.espeak_voice` is required even in\n",
       "`phoneme_ids` mode, where espeak is never called, and `--data.phoneme_type text` selects a\n",
       "phonemiser that is never used but avoids constructing the espeak one, whose compiled bridge\n",
       "a plain pip install does not build.\n"),
    md("## 8. Pick a checkpoint by measurement\n",
       "\n",
       "Not by the last step. Round-trip evaluation synthesises held-out phonemes, re-recognises\n",
       "them and measures unit error — automatic, and unlike validation loss it tracks whether the\n",
       "phonemes are actually being articulated.\n",
       "\n",
       "**Read the gap against the real-audio floor, not the raw number.** Feeding real recordings\n",
       "through gives the floor; the gap is what your model contributed.\n"),
    code("!ls runs/lightning_logs/version_0/checkpoints/\n",
         "\n",
         "# best by perceptual quality (UTMOS) and by reconstruction, then compare by ear\n",
         "import glob\n",
         "best_mos = sorted(glob.glob('runs/**/epoch=*val_mos*.ckpt', recursive=True))[-1]\n",
         "print('best val_mos:', best_mos)"),
    code("!python stable-twi-tts/training/synth.py \\\n",
         "    --checkpoint {best_mos} --config runs/config.json \\\n",
         "    --manifest tts22k/manifest_val.tsv --out synth --limit 100\n",
         "\n",
         "!python stable-twi-tts/training/tts_eval.py \\\n",
         "    --manifest tts22k/manifest_val.tsv \\\n",
         "    --synth-dir synth --real-dir tts22k/wav --limit 100"),
    md("## 9. Export a voice directory\n",
       "\n",
       "Produces `model.onnx`, `config.json`, `voices.json`, `tokens.txt` and optionally a lexicon.\n",
       "The ONNX export is not lossy — we measured 29.05% phoneme error against the PyTorch\n",
       "checkpoint's 30.22% on identical input.\n"),
    code("!python stable-twi-tts/tools/export_voice.py \\\n",
         "    --checkpoint {best_mos} --train-config runs/config.json \\\n",
         "    --manifest tts22k/manifest.tsv --out voices/my_twi_voice \\\n",
         "    --top-n 10 --min-hours 0.5\n",
         "!ls -la voices/my_twi_voice"),
    md("### Rank voices by measurement, not by hours\n",
       "\n",
       "`export_voice.py` ranks by training hours, which we found predicts almost nothing: our best\n",
       "code-switch voice was 21st of 30 on pure Twi, and two of the three best Twi voices had under\n",
       "3.3 h each. `tools/rank_voices.py` measures each voice instead.\n"),
    code("!python stable-twi-tts/tools/rank_voices.py \\\n",
         "    --voice-dir voices/my_twi_voice \\\n",
         "    --manifest tts22k/manifest_val.tsv \\\n",
         "    --synth-script stable-twi-tts/training/synth.py \\\n",
         "    --checkpoint {best_mos} --config runs/config.json \\\n",
         "    --asr-model ghananlpcommunity/ghana-speech-phoneme-asr \\\n",
         "    --per-voice 16"),
    PITFALLS,
])


# ---------------------------------------------------------------- from scratch

SCRATCH = notebook([
    md("# Train a Twi TTS model from scratch\n",
       "\n",
       "Trains a Piper VITS voice on IPA phonemes with no Twi checkpoint to start from.\n",
       "\n",
       "**Read this before choosing this notebook.** From scratch needs **days** of GPU time and\n",
       "far more data than finetuning. If you are working on Twi, or any language whose phonemes\n",
       "overlap the published inventory, `finetune.ipynb` will get you a better model in hours.\n",
       "\n",
       "This notebook is the right choice when:\n",
       "\n",
       "- you are training a **different language** whose inventory barely overlaps, or\n",
       "- you want a genuinely independent baseline.\n",
       "\n",
       "Even then, **warm-start from an English Piper checkpoint** rather than random init. We did:\n",
       "`libritts_r/medium` gave a working vocoder and speaker machinery for free, and 59 of our\n",
       "phoneme ids landed on its pretrained rows for the same sounds.\n"),
    GPU_CHECK, INSTALL, MONOTONIC, CLONE_TOOLS,
    *data_prep(scratch=True),
    md("## 4. Speaker labels\n",
       "\n",
       "Skip this if your data has real speaker ids. Ours did not: broadcast corpora are usually\n",
       "many-speaker and unlabelled, and training a single-speaker model on many voices yields an\n",
       "averaged, unstable timbre.\n",
       "\n",
       "Clustering x-vectors manufactures labels. 161k×161k pairwise distances is 100 GB, so this\n",
       "over-segments with k-means and agglomerates the *centroids* instead. The threshold errs toward\n",
       "splitting: over-splitting one speaker costs a model almost nothing, merging two muddies a voice.\n"),
    code("!pip install -q speechbrain scikit-learn\n",
         "!python stable-twi-tts/training/speaker_labels.py \\\n",
         "    --data data/data --embdir spk_emb --out speakers.parquet --threshold 0.7"),
    md("## 5. Warm-start checkpoint\n",
       "\n",
       "An English Piper checkpoint gives a trained vocoder and discriminators. Its speaker table is\n",
       "resized to your speaker count, with new rows seeded from real pretrained voices.\n"),
    code("from huggingface_hub import hf_hub_download\n",
         "base = hf_hub_download('rhasspy/piper-checkpoints',\n",
         "                       'en/en_US/libritts_r/medium/epoch=404-step=1887300.ckpt',\n",
         "                       repo_type='dataset')\n",
         "NSPK = !cut -d'|' -f2 tts22k/metadata_train_g2p.csv | sort -u | grep -c .\n",
         "NSPK = int(NSPK[0]); print('speakers:', NSPK)\n",
         "!python stable-twi-tts/training/adapt_checkpoint.py \\\n",
         "    --ckpt {base} --out warmstart.ckpt --num-speakers {NSPK}"),
    md("### Graft embeddings for symbols the base model already knows\n",
       "\n",
       "Where your phoneme exists in the base checkpoint's inventory, copy its learned embedding\n",
       "instead of starting random. Note the rescale: the two runs have different embedding scales, and\n",
       "copying raw vectors lands far outside the distribution the encoder expects — ours needed a 3.7×\n",
       "adjustment.\n"),
    code("# Optional: only if your map adds symbols the base checkpoint also has.\n",
         "# !python stable-twi-tts/training/graft_embeddings.py \\\n",
         "#     --ckpt warmstart.ckpt --pretrained {base} \\\n",
         "#     --graft tts22k/graft.json --out warmstart_grafted.ckpt"),
    md("## 6. Train\n",
       "\n",
       "Full learning rate here, unlike a finetune. Expect **days**, not hours: our bilingual run took\n",
       "~2 hours per epoch on an H200 at 0.72 it/s over 178k utterances.\n"),
    code("!python -m piper.train fit \\\n",
         "    --data.voice_name twi_scratch \\\n",
         "    --data.csv_path tts22k/metadata_train_g2p.csv \\\n",
         "    --data.audio_dir tts22k/wav \\\n",
         "    --data.dataset_type phoneme_ids \\\n",
         "    --data.phonemes_path tts22k/phonemes_g2p.json \\\n",
         "    --data.espeak_voice en-us \\\n",
         "    --data.phoneme_type text \\\n",
         "    --data.num_symbols 256 \\\n",
         "    --data.cache_dir runs/cache \\\n",
         "    --data.config_path runs/config.json \\\n",
         "    --data.batch_size 32 \\\n",
         "    --data.num_workers 8 \\\n",
         "    --data.validation_split 0.005 \\\n",
         "    --model.num_speakers {NSPK} \\\n",
         "    --model.sample_rate 22050 \\\n",
         "    --model.warmstart_ckpt warmstart.ckpt \\\n",
         "    --model.mos_metric utmos \\\n",
         "    --trainer.default_root_dir runs \\\n",
         "    --trainer.max_epochs -1 \\\n",
         "    --trainer.precision bf16-mixed \\\n",
         "    --trainer.val_check_interval 2000 \\\n",
         "    --trainer.accelerator gpu --trainer.devices 1"),
    md("## 7. Knowing when to stop\n",
       "\n",
       "Piper keeps top-5 by `val_mel` (reconstruction, lower better) and top-5 by `val_mos` (UTMOS\n",
       "perceptual, higher better). **Do not early-stop on `val_mel`** — it saturates while the\n",
       "adversarial losses are still removing audible artifacts.\n",
       "\n",
       "Our run, for a sense of shape:\n",
       "\n",
       "| | `val_mos` | `val_mel` |\n",
       "|---|---|---|\n",
       "| step 2k | 2.56 | 0.479 |\n",
       "| epoch 4 | 2.75 | 0.474 |\n",
       "| epoch 7 | **3.02** | 0.469 |\n",
       "\n",
       "`val_mel` got *worse* for two epochs mid-run while the encoder absorbed new symbols, then\n",
       "recovered. Stopping on it would have fired early.\n",
       "\n",
       "Treat convergence as *both* `val_mos` and round-trip phoneme error plateauing — then choose\n",
       "between the surviving checkpoints by listening.\n"),
    code("!python stable-twi-tts/training/synth.py \\\n",
         "    --checkpoint runs/lightning_logs/version_0/checkpoints/last.ckpt \\\n",
         "    --config runs/config.json --manifest tts22k/manifest_val.tsv \\\n",
         "    --out synth --limit 100\n",
         "!python stable-twi-tts/training/tts_eval.py \\\n",
         "    --manifest tts22k/manifest_val.tsv --synth-dir synth \\\n",
         "    --real-dir tts22k/wav --limit 100"),
    md("## 8. Export\n",
       "\n",
       "Same as the finetune notebook — see its final sections for exporting a voice directory and\n",
       "ranking voices by measured quality rather than by training hours.\n"),
    code("!python stable-twi-tts/tools/export_voice.py \\\n",
         "    --checkpoint runs/lightning_logs/version_0/checkpoints/last.ckpt \\\n",
         "    --train-config runs/config.json --manifest tts22k/manifest.tsv \\\n",
         "    --out voices/twi_scratch --top-n 10 --min-hours 0.5 --lexicon"),
    PITFALLS,
])


def main() -> None:
    out = Path(__file__).parent
    for name, nb in (("finetune.ipynb", FINETUNE),
                     ("train_from_scratch.ipynb", SCRATCH)):
        (out / name).write_text(json.dumps(nb, indent=1, ensure_ascii=False),
                                encoding="utf-8")
        n_md = sum(1 for c in nb["cells"] if c["cell_type"] == "markdown")
        n_code = sum(1 for c in nb["cells"] if c["cell_type"] == "code")
        print(f"{name}: {n_md} markdown + {n_code} code cells")


if __name__ == "__main__":
    main()
